Models/ErrorViewModel.cs
using System;

namespace DefaultCalendar.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Event.cs
namespace DefaultCalendar.Models
{
    public class Event
    {
        public int EventId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
        public bool AllDay { get; set; }
    }
}

Controllers/CalendarController.cs
using System.Linq;
using DefaultCalendar.Data;
using DefaultCalendar.Models;
using Microsoft.AspNetCore.Mvc;

namespace DefaultCalendar.Controllers
{
    public class CalendarController: Controller
    {
        private readonly ApplicationDbContext _context;
        public CalendarController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var listaModelo = _context.Event.ToList();      
            return View(listaModelo);
        }


        public IActionResult Create(string date)
        {
            var modelo = new Event() {
                Start = date,
            };
            return PartialView("_CreateEvent", modelo);
        }


        [HttpPost]
        public IActionResult Create(Event modelo)
        {
            _context.Add(modelo);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult Edit(int eventId)
        {
            var modelo = _context.Event.Single(x => x.EventId == eventId);
            return PartialView("_EditEvent", modelo);
        }


        [HttpPost]
        public IActionResult Edit(Event modelo)
        {
            _context.Update(modelo);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DefaultCalendar.Models;

namespace DefaultCalendar.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calendar/Index.cshtml
@model IEnumerable<DefaultCalendar.Models.Event>

<link href='~/lib/fullcalendar/main.css' rel='stylesheet' />
<script src='~/lib/fullcalendar/main.js'></script>

<div id='calendar'></div>

<script>

    document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {

        dateClick: function(info) {
            CreateEvent(info.dateStr);            
        },

        eventClick: function(info) {
            EditEvent(info.event.id);

            // change the border color just for fun
            info.el.style.borderColor = 'red';
        },

        headerToolbar: {  
            left: 'prevYear,prev,next,nextYear today',
            center: 'title',
            right: 'dayGridMonth,dayGridWeek,dayGridDay'
        },
        initialDate: new Date(),
        navLinks: true, // can click day/week names to navigate views
        editable: true,
        dayMaxEvents: true, // allow "more" link when too many events
        
        events: [        
            @foreach (var item in Model)
            {
                <Text>
                    {
                        id: '@item.EventId',
                        title: '@item.Title',
                        start: '@item.Start',                        
                    },
                </Text>
            }
           
        ]



    });

    calendar.render();
  });

</script>



<div id='carrega-modal'></div>


<partial name="_style" />
<partial name="_scripts" />

Views/Calendar/_CreateEvent.cshtml
@model DefaultCalendar.Models.Event

<div class="modal fade" id="modalCreateEvent" role="dialog" aria-labelledby="eventModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="Create">
                <div class="modal-header">
                    <h4 class="modal-title" id="eventModalLabel">Event</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">                
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Title</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" asp-for="Title">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Start Time</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" asp-for="Start">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">End Time</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" asp-for="End">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <textarea class="form-control" asp-for="Description" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-3 offset-sm-9">
                                <label><input type="checkbox" asp-for="AllDay" /> All Day</label>
                            </div>
                        </div>                            
                </div>
                <div class="modal-footer">
                    <div>
                        <input type="submit" class="btn btn-primary" value="Create" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Calendar/_EditEvent.cshtml
@model DefaultCalendar.Models.Event

<div class="modal fade" id="modalEditEvent" role="dialog" aria-labelledby="eventModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="Edit">
                <div class="modal-header">
                    <h4 class="modal-title" id="eventModalLabel">Event</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">    
                        <input type="hidden" asp-for="EventId"/>       
                             
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Title</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" asp-for="Title">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Start Time</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" asp-for="Start">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">End Time</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" asp-for="End">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class="col-sm-3 col-form-label">Description</label>
                            <div class="col-sm-9">
                                <textarea class="form-control" asp-for="Description" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-3 offset-sm-9">
                                <label><input type="checkbox" asp-for="AllDay" /> All Day</label>
                            </div>
                        </div>                            
                </div>
                <div class="modal-footer">
                    <div>
                        <input type="submit" class="btn btn-primary" value="Update" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Calendar/_scripts.cshtml
<script>

    function CreateEvent(strDate) {

        var rota = '@Url.Action("Create","Calendar")';

        $.get(rota, { date: strDate }, function (data)
        {
            $("#carrega-modal").html(data);
            $('#modalCreateEvent').modal('show');
        })
        .fail(function() {
            alert("Erro interno");
        }); 
    }


    function EditEvent(id) {

        var rota = '@Url.Action("Edit","Calendar")';

        $.get(rota, { eventId: id }, function (data)
        {
            $("#carrega-modal").html(data);
            $('#modalEditEvent').modal('show');
        })
        .fail(function() {
            alert("Erro interno");
        }); 
    }
    
  
</script>

Views/Calendar/_style.cshtml
<style>

  body {
    margin: 40px 10px;
    padding: 0;
    font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
    font-size: 14px;
  }

  #calendar {
    max-width: 1100px;
    margin: 0 auto;
  }

</style>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DefaultCalendar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DefaultCalendar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DefaultCalendar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>